.oh-my-zsh:
    type: "archive"
    url: "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact: true
    stripComponents: 1
    refreshPeriod: "168h"

".local/share/nvim/site/autoload":
    type: "file"
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod: "168h"
".local/share/nvim/plugged":
    type: "archive"
    url: "https://github.com/dracula/vim/archive/master.tar.gz"
    refreshPeriod: "168h"

".tmux/plugins/tmux-cpu":
    type: "archive"
    url: "https://github.com/tmux-plugins/tmux-cpu/archive/master.tar.gz"
    refreshPeriod: "168h"
    exact: true
".tmux/plugins/tmux-resurrect":
    type: "archive"
    url: "https://github.com/tmux-plugins/tmux-resurrect/archive/master.tar.gz"
    refreshPeriod: "168h"
    exact: true
".tmux/plugins/tmux-sensible":
    type: "archive"
    url: "https://github.com/tmux-plugins/tmux-sensible/archive/master.tar.gz"
    refreshPeriod: "168h"
    exact: true
".tmux/plugins/tmux":
    type: "archive"
    url: "https://github.com/dracula/tmux/archive/master.tar.gz"
    refreshPeriod: "168h"
    exact: true
".tmux/plugins/tpm":
    type: "archive"
    url: "https://github.com/tmux-plugins/tpm/archive/master.tar.gz"
    refreshPeriod: "168h"
    exact: true
