".local/share/nvim/site/autoload/plug.vim":
    type: "file"
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod: "168h"
".local/share/nvim/plugged":
    type: "archive"
    url: "https://github.com/dracula/vim/archive/master.tar.gz"
    refreshPeriod: "168h"
